### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by nrbnlulu** [nrbnlulu/strawberry-django-auth#5]
- [x] ~~support for allow-any-classes equivalent~~ - users should use strawberry builtin way for permission handleing or strawberry django plus permission directives.

- [x] <s> implement relay compatible queries keeping in mind some user don't use relay </s> This can be done with strawberry django plus.
- [ ] 
- [ ] #269  

- [x] migrate to async resolvers keeping in mind some user prefer sync  

- [ ] #214 

### Docs

- [x]   #3
